[workspace]
members = ["compiler/*"]
resolver = "2"

[workspace.dependencies]
rustc_span = "0.1.2"
ariadne = { version = "0.5.1", features = ["auto-color"] }
internment = {version = "0.8.6", features = ["arena"]}
once_cell = "1.21.3"
rustc_data_structures = "0.1.2"