[package]
name = "vfs"
version = "0.1.0"
edition = "2024"

[dependencies]
diagnostic = { path = "../diagnostic" }
ast = { path = "../ast" }
parse = { path = "../parse" }
rustc_data_structures = { workspace = true }
rustc_span = { workspace = true }